name: lamanna
favicon: null
layout_spectrum: 0.3379166356753558
typography_spectrum: 0.5060113384388387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.39318810193799436
  lightness: 0.8573915038723499
  saturation: 0.5657607642933726
  rhythmicContrast: 0.8545911791734397
purpose: []
